"""recon core schema

Revision ID: ffee7718ca39
Revises: 
Create Date: 2026-08-08 17:03:00.517658

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffee7718ca39'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('account_code', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'account_code', name='ledger_entry_transfer_account_uq')
    )
    op.create_index('ledger_entry_external_idx', 'ledger_entry', ['external_id'], unique=False)
    op.create_index('ledger_entry_occurred_idx', 'ledger_entry', ['account_code', 'occurred_at'], unique=False)
    op.create_table('statement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('account_code', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('recon_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_code', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('statement_id', sa.String(length=36), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('ledger_count', sa.Integer(), nullable=False),
    sa.Column('statement_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('break_count', sa.Integer(), nullable=False),
    sa.Column('unexplained_minor', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('recon_run_started_idx', 'recon_run', ['started_at'], unique=False)
    op.create_table('statement_line',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('statement_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_id', 'line_no', name='statement_line_no_uq')
    )
    op.create_index('statement_line_value_date_idx', 'statement_line', ['value_date'], unique=False)
    op.create_table('recon_break',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('ledger_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee', sa.String(length=128), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_run_id', sa.String(length=36), nullable=True),
    sa.Column('recurrence', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recon_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('recon_break_open_idx', 'recon_break', ['is_open', 'type'], unique=False)
    op.create_index('recon_break_run_idx', 'recon_break', ['run_id'], unique=False)
    op.create_table('recon_match',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('ledger_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delta_minor', sa.BigInteger(), nullable=False),
    sa.Column('date_gap_days', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recon_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('recon_match_run_rule_idx', 'recon_match', ['run_id', 'rule'], unique=False)
    op.create_table('break_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('break_id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['break_id'], ['recon_break.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('break_event')
    op.drop_index('recon_match_run_rule_idx', table_name='recon_match')
    op.drop_table('recon_match')
    op.drop_index('recon_break_run_idx', table_name='recon_break')
    op.drop_index('recon_break_open_idx', table_name='recon_break')
    op.drop_table('recon_break')
    op.drop_index('statement_line_value_date_idx', table_name='statement_line')
    op.drop_table('statement_line')
    op.drop_index('recon_run_started_idx', table_name='recon_run')
    op.drop_table('recon_run')
    op.drop_table('statement')
    op.drop_index('ledger_entry_occurred_idx', table_name='ledger_entry')
    op.drop_index('ledger_entry_external_idx', table_name='ledger_entry')
    op.drop_table('ledger_entry')
    # ### end Alembic commands ###
